### ISSUE TITLE
Weather is totally fine but there is a bug in location, keep it in mind.

### ISSUE THREAD

**Issue by SBSojib** [SBSojib/Agrismart#14]

**Comment by tanzimulhoq** [comment]
Whats the bug?

**Comment by SBSojib** [comment]
Abeee, kutte, aise he dimag kharab ho raha hain tera khud ki kam karne main, ab mere bug janke kya karega tu? Bola hain bus dimag main dal rakh. Main solve kar dunga.

**Comment by SBSojib** [comment]
The bug is fixed.
Thank You
