### ISSUE TITLE
Xml file orientation is wrong

### ISSUE THREAD

**Issue by tanzimulhoq** [SBSojib/Agrismart#26]
The xml file admin_page.xml has a wrong orientation and is not being corrected.

**Comment by SBSojib** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:fillViewport="false">
    <LinearLayout
        android:orientation="vertical" android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        >
        <TextView
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:background="@color/colorPrimaryDark"
            android:text="Add Crop"
            android:textSize="25dp"
            android:gravity="center"

            android:textColor="@android:color/white"
            android:fontFamily="sans-serif-black"/>

        <EditText
            android:id="@+id/crpName"
            android:layout_width="270dp"
            android:layout_height="41dp"
            android:layout_marginTop="20dp"
            android:background="@android:color/white"
            android:hint="Crop Name" />

        <EditText
            android:hint="Latitude"
            android:id="@+id/crpLat"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />

        <EditText
            android:hint="Longitude"
            android:id="@+id/crpLon"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />

        <EditText
            android:hint="Month"
            android:id="@+id/crpMon"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />

        <EditText
            android:hint="Minimum Temperature"
            android:id="@+id/minTempOfCrop"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />

        <EditText
            android:hint="Maximum Temperature"
            android:id="@+id/maxTempOfCrop"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />

        <EditText
            android:hint="Minimum Humidity"
            android:id="@+id/minHumidityOfCrop"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />

        <EditText
            android:hint="Maximum Humidity"
            android:id="@+id/maxHumidityOfCrop"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />

        <EditText
            android:hint="Interval of Fertilizing"
            android:id="@+id/fertilizingIntervalOfCrop"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />
        <EditText
            android:hint="Total Feritlization Time"
            android:id="@+id/totalFertiliaztionTimeOfCrop"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />
        <EditText
            android:hint="Interval of Insecticide"
            android:id="@+id/insecticideIntervalOfCrop"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />
        <EditText
            android:hint="Total Insecticide Time"
            android:id="@+id/totalInsecticideTimeOfCrop"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />
        <EditText
            android:hint="Cultivation Duration"
            android:id="@+id/cultivationDurationOfCrop"
            android:inputType="number"
            android:layout_width="270dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:background="@android:color/white" />
        <Button
            android:background="@drawable/rounded_button"
            android:id="@+id/addFileFert"
            android:layout_width="154dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="20dp"
            android:text="Fertilizer" />
        <Button
            android:background="@drawable/rounded_button"
            android:id="@+id/addFilePest"
            android:layout_width="154dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:text="Pesticide" />
        <Button
            android:background="@drawable/rounded_button"
            android:id="@+id/addFilePrc"
            android:layout_width="154dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:text="Price" />

        <Button
            android:background="@drawable/rounded_button"
            android:id="@+id/addcrop"
            android:layout_width="154dp"
            android:layout_height="40dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:text="ADD" />

    </LinearLayout>
</ScrollView>

**Comment by SBSojib** [comment]
I believe your problem is solved now, you messed up because of using drag and drop, you should have try raw code, it's better.
